on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: publish Xaringan presentations

jobs:
  publish:
    runs-on: ubuntu-18.04
    env:
      RSPM: https://packagemanager.rstudio.com/cran/__linux__/bionic/latest
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        id: install-r

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Install dependencies
        run: |
          install.packages("xaringan")
          install.packages("xaringanthemer")
          install.packages("devtools")
          devtools::install_github("gadenbuie/xaringanExtra")
        shell: Rscript {0}


      - name: Build xaringan presentation
        run: |
          Rscript -e 'rmarkdown::render("README.md", output_format = "html_document", output_file = "index.html", output_dir = "public")'
          Rscript -e 'rmarkdown::render("FOSS4G_2021/presentation.Rmd", output_file = "FOSS4G2021.html", output_dir = "public")'

      - name: Copy non-xaringan presentations
        run: |
          cp 2019_SAGEO/2019_SAGEO_ARABESQUE_presentation.pdf public/2019_SAGEO_ARABESQUE_presentation.pdf
          cp 2020_FOSDEM/20200202_geospatial_Arabesque_ROELANDT_FOSDEM2020.pdf public/20200202_geospatial_Arabesque_ROELANDT_FOSDEM2020.pdf
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public