on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: publish Xaringan presentations

jobs:
  publish:
    runs-on: ubuntu-18.04
    env:
      RSPM: https://packagemanager.rstudio.com/cran/__linux__/bionic/latest
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        id: install-r

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Install dependencies
        run: |
          install.packages("xaringan")
          install.packages("xaringanthemer")
        shell: Rscript {0}


      - name: Build xaringan presentation
        run: |
          mkdir ./public
          Rscript -e 'rmarkdown::render("index.Rmd", output_file = "./public/index.html")'
          Rscript -e 'rmarkdown::render("FOSS4G_2021/presentation.Rmd", output_file = "./public/FOSS4G2021.html")'
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public