on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: publish Xaringan presentations

jobs:
  publish:
    runs-on: ubuntu-18.04
    env:
      RSPM: https://packagemanager.rstudio.com/cran/__linux__/bionic/latest
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
        with:
          ref: github-pages

      - uses: r-lib/actions/setup-r@v1
        id: install-r

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Query dependencies
        run: |
          install.packages('remotes')
        shell: Rscript {0}

      - name: Install dependencies
        run: |
          remotes::install_deps(dependencies = TRUE)
          install.packages("pkgdown", type = "binary")
          install.packages("xaringan", type = "binary")
          install.packages("xaringanthemer", type = "binary")
        shell: Rscript {0}


      - name: Build and deploy xaringan presentation
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          Rscript -e 'rmarkdown::render("index.Rmd")'
          Rscript -e 'rmarkdown::render("FOSS4G_2021/presentation.Rmd")'
          
      - name: Commit and push
        run: |
          git add .
          git commit -m "Render presentation"
          git push origin github-pages
